---
- name: Ansible playbook for all hosts
  hosts: all
  vars_files:
    - vars/vault.yml
  vars:
    ansible_become_pass: "{{ vault_ansible_become_pass }}"
  roles:
    - fedora
  remote_user: ansible
  tags: fedora

- name: Ansible playbook for configuring Reverse Proxy
  hosts: proxy
  vars_files:
    - vars/vault.yml
  vars:
    ansible_become_pass: "{{ vault_caddy_become_pass }}"
  roles:
    - proxy
  remote_user: caddy
  tags: proxy
