---
- name: Update DNF package cache
  become: yes
  dnf:
    update_cache: yes

- name: Upgrade all packages
  become: yes
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: yes
  notify: reboot

- name: Install dnf-automatic for unattended updates
  become: yes
  ansible.builtin.dnf:
    name:
      - dnf-automatic
    state: present

- name: Check if /etc/dnf/automatic.conf exists
  stat:
    path: /etc/dnf/automatic.conf
  register: dnf_automatic_conf

- name: Create /etc/dnf/automatic.conf if it doesn't exist
  copy:
    dest: /etc/dnf/automatic.conf
    content: ""
    owner: root
    group: root
    mode: '0644'
  become: yes
  when: not dnf_automatic_conf.stat.exists

- name: Configure dnf-automatic for security updates
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/dnf/automatic.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^upgrade_type =', line: 'upgrade_type = security' }
    - { regexp: '^download_updates =', line: 'download_updates = yes' }
    - { regexp: '^apply_updates =', line: 'apply_updates = yes' }
    - { regexp: '^emit_via =', line: 'emit_via = email' }
    - { regexp: '^email_to =', line: 'email_to = root' }

- name: Enable and start dnf-automatic timer
  become: yes
  ansible.builtin.systemd:
    name: dnf-automatic.timer
    enabled: yes
    state: started

- name: Install packages
  become: yes
  dnf:
    name:
      - git
      - ca-certificates
      - wget
      - dnf-plugins-core
      - gnupg2
      - curl
      - python3-pip
      - podman
    state: present
